# $$Pandas$$

- Pandas is a python library
- provides fast, flexible, and expressive data structures designed to make working with tables easy
- Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
- [Documentation](https://pandas.pydata.org/docs/getting_started/overview.html)
- 
- Data Structures in pandas are:

Dimensions | Name | Description
----|---|---
1 | Series  | 1D   labeled homogeneously-typed array
2 | DataFrame | General 2D   labeled, size-mutable tabular structure with potentially heterogeneously-typed column

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg)

- main purpose is commonly ---> data prepration / data pre-processing
- You can explore, clean, and transform data before analytics or building ML Models
- 
-  we can :
    - Read from csv files
    - select rows and columns
    - filter, sort, group data
    - handle missing values
    - prepare data for analytics or ML

In [30]:
# pip install pandas

In [31]:
import numpy as np
import pandas as pd

data = np.arange(1,10)* 10
type(data)

series_a = pd.Series(data, name= "data")
print(series_a)
# you will observe index has been added

type(series_a)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
Name: data, dtype: int64

pandas.Series

In [32]:
pd.DataFrame([series_a,series_a,series_a,series_a])

       0   1   2   3   4   5   6   7   8
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90

In [33]:
dataframe_a = pd.DataFrame(data)
dataframe_a = pd.DataFrame([series_a,series_a,series_a,series_a]) # the name will turn to label

# naming columns
cols = ['series1', 'series2', 'series3','series4','series5','series6','series7','series8']

dataframe_a = pd.DataFrame([series_a,series_a,series_a,series_a],
                        #    columns= cols
)

print(dataframe_a)
# type(dataframe_a)

       0   1   2   3   4   5   6   7   8
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90
data  10  20  30  40  50  60  70  80  90

In [69]:
data = {
    "student": ["aqilah","Nazihah","Alia"],
    "maths": [88, 92, 85],
    "science": [95,96,98],
    "physics": [68, 78, 61]
}

marks_df = pd.DataFrame(data)
marks_df

   student  maths  science  physics
0   aqilah     88       95       68
1  Nazihah     92       96       78
2     Alia     85       98       61

#### Data structures
- SERIES:
    - INDEX ---> number assigned to each row
    - No label---> assigned to columns
    - Name - can have a series name

- DATAFRAME:
    - LABEL ---> column name --- By default it will serially done ---
        - starts from 0 
    - INDEX ---> number for each row
    - 
- Create:
    - using lists, arrays, dictionaries, list of dictionaries
    - reading a csv file, or an SQL file, or any spreadsheet
    -

#### Exercise
1. Create a `pd.Series` with 5 temperature values and print it.
2. Create a pd.DataFrame with columns "`City`" and "`Temperature`" for 3 cities.
3. Check the `type()` of each object you created.
4. Add a name to your Series and print it again.

In [49]:
# 5 random temperature
temp = pd.Series([27, 31, -2, 10, 11], name = "Temperature")
print("Temperature")
print(temp)
print(f"Type of #1: {type(temp)}")
 
print("="*30)
 
# city's temperature
city_temps = {
    "City": ["Kuala Lumpur", "Leipzig", "Kashmir", "London", "Tokyo"],
    "Temperature": [31, 7, 10, 23, 25]
}
 
temp_df = pd.DataFrame(city_temps)
print(temp_df)
print(f"Type of #2: {type(temp_df)}")
 
print("="*30)

Temperature
0    27
1    31
2    -2
3    10
4    11
Name: Temperature, dtype: int64
Type of #1: <class 'pandas.Series'>
==============================
           City  Temperature
0  Kuala Lumpur           31
1       Leipzig            7
2       Kashmir           10
3        London           23
4         Tokyo           25
Type of #2: <class 'pandas.DataFrame'>
==============================

In [45]:
city_temps = [
    {"city": "Kuala Lumpur", "Temperature":31},
    {"city": "Leipzig", "Temperature":7},
    {"city": "Kashmir", "Temperature":10},
    {"city": "London", "Temperature":23},
    {"city": "Tokyo", "Temperature":25},
    {"city": "Helsiki", }
]

In [63]:
# city's temperature
city_temps = {
    "City": ["Kuala Lumpur", "Leipzig", "Kashmir", "London", "Tokyo"],
    "Temperature": [31, 7, 10, 23, 25]
}

city_temps = [
    {"city": "Kuala Lumpur", "Temperature":31},
    {"city": "Leipzig", "Temperature":7},
    {"city": "Kashmir", "Temperature":10},
    {"city": "London", "Temperature":23},
    {"city": "Tokyo", "Temperature":25},
    {"city": "Helsiki" , "Temperature": None}
]
 
temp_df = pd.DataFrame(city_temps)
temp_df

           city  Temperature
0  Kuala Lumpur         31.0
1       Leipzig          7.0
2       Kashmir         10.0
3        London         23.0
4         Tokyo         25.0
5       Helsiki          NaN

#### Nan Values
- Missing Values - 
    - np.nan in a dataframe
    - or we can also have None type data in a dataframe

##### Basic Exploration

- some methods that can be used on DataFrames
    - `df.head()` - first 5 records/rows
    - `df.tail` - ending 5
    - `df.sample()` - random entry from df
    - pass in the argument for how many records you want

In [78]:
marks_df.head()
marks_df.tail()
marks_df.sample()

  student  maths  science  physics
2    Alia     85       98       61

## Basic data accessing in a dataframe
- access a single column --- using `[]` or `.` operator
    - `df['column_name']` ---> Return a series object
    - show the `name` and the `data type` as well
    - 
- access a value in a column
    - `df['column_name'][index_value]` ---> gets to a particular value

In [64]:
temp_df['city'][5]
type(temp_df['city'][5])

type(temp_df['Temperature'][5]) # Nan values in dataframes are empty numpy values

temp_df.Temperature

0    31.0
1     7.0
2    10.0
3    23.0
4    25.0
5     NaN
Name: Temperature, dtype: float64

#### Reading from CSV file
- CSV - Comma Separated Values
- Let's download a csv file from here [>>>> Link...](https://github.com/yannie28/Global-Superstore/blob/master/Global_Superstore(CSV).csv)
-

In [ ]:
path = r"C:\Users\devid\Desktop\Nexperts Academy\AIML-nexperts4\Resources\Global_Superstore(CSV).csv"
df = pd.read_csv(path)

In [88]:
df.head(15)
# df.tail(50)
# df.sample(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High
1,26341,IN-2014-JR162107-41675,2/5/2014,2/7/2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.16,Medium
4,47221,SG-2014-RH9495111-41948,11/5/2014,11/6/2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,6/28/2014,7/1/2014,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.68,5,0.1,763.28,897.35,Critical
6,30570,IN-2012-TS2134092-41219,11/6/2012,11/8/2012,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.08,4,0.0,564.84,894.77,Critical
7,31192,IN-2013-MB1808592-41378,4/14/2013,4/18/2013,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.84,6,0.0,996.48,878.38,High
8,40099,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.96,2,0.0,54.71,25.27,High
9,36258,CA-2012-AB10015140-40974,3/6/2012,3/7/2012,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,FUR-CH-4421,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.71,1,0.2,5.48,11.13,High
10,36259,CA-2012-AB10015140-40974,3/6/2012,3/7/2012,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,OFF-AR-5309,Office Supplies,Art,Newell 330,17.94,3,0.0,4.66,4.29,High
11,28879,ID-2013-AJ107801-41383,4/19/2013,4/22/2013,First Class,AJ-107801,Anthony Jacobs,Corporate,NaN,Kabul,...,FUR-TA-3420,Furniture,Tables,"Bevis Conference Table, Fully Assembled",4626.15,5,0.0,647.55,835.57,High
12,45794,SA-2012-MM7260110-41269,12/26/2012,12/28/2012,Second Class,MM-7260110,Magdelene Morse,Consumer,NaN,Jizan,...,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.96,4,0.0,1151.40,832.41,Critical
13,4132,MX-2013-VF2171518-41591,11/13/2013,11/13/2013,Same Day,VF-2171518,Vicky Freymann,Home Office,NaN,Toledo,...,FUR-CH-4530,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.80,7,0.0,622.02,810.25,Critical
14,27704,IN-2014-PF1912027-41796,6/6/2014,6/8/2014,Second Class,PF-1912027,Peter Fuller,Consumer,NaN,Mudanjiang,...,OFF-AP-4959,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.52,12,0.0,1036.08,804.54,Critical